

    - name: Install dependencies command
      if: ${{ env.KASSETT_INSTALL_DEPENDENCIES_COMMAND != '' }}
      shell: bash
      run: |
        source venv/bin/activate
        printf 'env.KASSETT_INSTALL_DEPENDENCIES_COMMAND=%q\n' "${{ env.KASSETT_INSTALL_DEPENDENCIES_COMMAND }}"


    - name: Run test command
      if: ${{ env.KASSETT_TEST_COMMAND != '' }}
      shell: /usr/bin/bash -e {
      run: |
        source venv/bin/activate
        cm="make setup"
        eval  $"( "${cm}" )" 

    - name: Build Dependencies for Twine
      if: ${{ env.KASSETT_PUBLISH_PACKAGE_USING == 'twine' && env.KASSETT_CUSTOM_BUILD_COMMAND == '' }}
      shell: bash
      run: |
        source venv/bin/activate
        pip install twine wheel setuptools

    - name: Build Twine
      if: ${{ env.KASSETT_PUBLISH_PACKAGE_USING == 'twine' && env.KASSETT_CUSTOM_BUILD_COMMAND == '' }}
      shell: bash
      run: |
        source venv/bin/activate
        python setup.py sdist bdist_wheel

    - name: Custom Build
      if: ${{ env.KASSETT_CUSTOM_BUILD_COMMAND != '' }}
      shell: bash
      run: |
        source venv/bin/activate
        eval $KASSETT_CUSTOM_BUILD_COMMAND

    - name: Upload Twine
      if: ${{ env.KASSETT_PUBLISH_PACKAGE_USING == 'twine' }}
      shell: bash
      run: |
        source venv/bin/activate
        twine upload dist/*
      env:
        TWINE_USERNAME: ${{ env.KASSETT_PYPI_USERNAME }}
        TWINE_REPOSITORY: ${{ env.KASSETT_PYPI_REPO_URL }}
        TWINE_PASSWORD: ${{ env.KASSETT_PYPI_PASSWORD }}

    - name: Upload Poetry
      if: ${{ env.KASSETT_PUBLISH_PACKAGE_USING == 'poetry' && env.KASSETT_CUSTOM_BUILD_COMMAND == '' }}
      shell: bash
      run: |
        source venv/bin/activate
        poetry config repositories.prod ${REPOSITORY_URL}
        poetry config http-basic.${REPOSITORY_NAME} ${REPOSITORY_USERNAME} ${REPOSITORY_PASSWORD}
        (yes || true) | poetry publish --build --repository ${REPOSITORY_NAME}
      env:
        REPOSITORY_NAME: ${{ env.KASSETT_PYPI_REPO_NAME }}
        REPOSITORY_URL: ${{ env.KASSETT_PYPI_REPO_URL }}
        REPOSITORY_USERNAME: ${{ env.KASSETT_PYPI_USERNAME }}
        REPOSITORY_PASSWORD: ${{ env.KASSETT_PYPI_PASSWORD }}


    
    


